insert into OrderStatus (orderStatusCod, orderStatusDesc) values (1, 'morbi a ipsum integer a nibh in quis justo maecenas');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (2, 'consequat metus sapien ut nunc vestibulum ante');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (3, 'dapibus duis at velit eu est congue');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (4, 'tempus vel pede morbi porttitor lorem');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (5, 'egestas metus aenean fermentum donec ut mauris eget');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (6, 'cursus vestibulum proin eu mi nulla ac enim');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (7, 'ut tellus nulla ut erat id mauris vulputate elementum');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (8, 'id nisl venenatis lacinia aenean sit amet justo morbi');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (9, 'consequat ut nulla sed accumsan');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (10, 'mi integer ac neque duis bibendum morbi non');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (11, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (12, 'maecenas leo odio condimentum id luctus');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (13, 'est congue elementum in hac habitasse');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (14, 'mattis nibh ligula nec sem duis aliquam convallis');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (15, 'et ultrices posuere cubilia curae nulla');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (16, 'cras pellentesque volutpat dui maecenas');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (17, 'sapien cursus vestibulum proin eu');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (18, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (19, 'lacus at velit vivamus vel nulla eget');
insert into OrderStatus (orderStatusCod, orderStatusDesc) values (20, 'adipiscing elit proin interdum mauris non ligula pellentesque');
