insert into OrderStatus ( orderStatusDesc) values ( 'morbi a ipsum integer a nibh in quis justo maecenas');
insert into OrderStatus ( orderStatusDesc) values ('consequat metus sapien ut nunc vestibulum ante');
insert into OrderStatus ( orderStatusDesc) values ( 'dapibus duis at velit eu est congue');
insert into OrderStatus ( orderStatusDesc) values ( 'tempus vel pede morbi porttitor lorem');
insert into OrderStatus ( orderStatusDesc) values ( 'egestas metus aenean fermentum donec ut mauris eget');
insert into OrderStatus ( orderStatusDesc) values ( 'cursus vestibulum proin eu mi nulla ac enim');
insert into OrderStatus ( orderStatusDesc) values ( 'ut tellus nulla ut erat id mauris vulputate elementum');
insert into OrderStatus ( orderStatusDesc) values ( 'id nisl venenatis lacinia aenean sit amet justo morbi');
insert into OrderStatus ( orderStatusDesc) values ( 'consequat ut nulla sed accumsan');
insert into OrderStatus ( orderStatusDesc) values ( 'mi integer ac neque duis bibendum morbi non');
insert into OrderStatus ( orderStatusDesc) values ( 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into OrderStatus ( orderStatusDesc) values ( 'maecenas leo odio condimentum id luctus');
insert into OrderStatus (orderStatusDesc) values ( 'est congue elementum in hac habitasse');
insert into OrderStatus ( orderStatusDesc) values ( 'mattis nibh ligula nec sem duis aliquam convallis');
insert into OrderStatus ( orderStatusDesc) values ( 'et ultrices posuere cubilia curae nulla');
insert into OrderStatus ( orderStatusDesc) values ( 'cras pellentesque volutpat dui maecenas');
insert into OrderStatus ( orderStatusDesc) values ( 'sapien cursus vestibulum proin eu');
insert into OrderStatus ( orderStatusDesc) values ( 'erat fermentum justo nec condimentum neque sapien placerat ante nulla');
insert into OrderStatus ( orderStatusDesc) values ( 'lacus at velit vivamus vel nulla eget');
insert into OrderStatus ( orderStatusDesc) values ( 'adipiscing elit proin interdum mauris non ligula pellentesque');
